production:
  sync_live_scores:
    class: SyncLiveScoresJob
    schedule: "every 1 minute"
    queue: default

  sync_live_matches:
    class: SyncLiveMatchesJob
    schedule: "every 1 minute"
    queue: default

  sync_today_matches:
    class: SyncTodayMatchesJob
    schedule: "every 10 minutes"
    queue: default

  sync_standings:
    class: SyncStandingsJob
    schedule: "every 30 minutes"
    queue: default
